'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { BarChart3, Bot, CheckCircle2, MessageSquare, Star, ThumbsDown, TrendingUp, UserRoundCheck, Users } from 'lucide-react'
import { DashboardLayout } from '@/components/DashboardLayout'
import { LoadingSpinner } from '@/components/ui/LoadingSpinner'
interface Data{periodDays:number;summary:{conversations:number;messages:number;resolved:number;handoffs:number;identifiedContacts:number;positiveFeedback:number;negativeFeedback:number;satisfaction:number|null;averageMessages:number};intents:{label:string;value:number}[];sentiments:{label:string;value:number}[];byAgent:{id:string;name:string;conversations:number;messages:number;resolved:number;handoffs:number}[];daily:{date:string;value:number}[];attention:{id:string;name:string;agent:string;reason:string|null;lastInteraction:string}[];negativeFeedback:{id:string;conversationId:string;feedbackComment:string|null;content:string;createdAt:string}[];pipeline:{stages:{stage:string;calls:number;successes:number;totalLatencyMs:number;averageLatencyMs:number;successRate:number;totalCostUsd:number;totalTokens:number}[];aiCostUsd:number;aiTokens:number;aiCalls:number}}
export default function AnalyticsPage(){const [data,setData]=useState<Data|null>(null);const [days,setDays]=useState(30);const [loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);fetch(`/api/analytics?days=${days}`).then(r=>r.json()).then(result=>setData(result.success?result.data:null)).finally(()=>setLoading(false))},[days]);if(loading||!data)return <DashboardLayout><LoadingSpinner fullPage text="Calcolo qualità e performance..."/></DashboardLayout>;const s=data.summary
return <DashboardLayout><div className="mx-auto max-w-[1500px] p-5 lg:p-7"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Quality intelligence</p><h1 className="mt-1 text-2xl font-bold text-gray-950">Analytics</h1><p className="mt-1 text-sm text-gray-500">Prestazioni reali degli agenti, qualità delle risposte e problemi da correggere.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))} className="input w-44 text-xs"><option value={7}>Ultimi 7 giorni</option><option value={30}>Ultimi 30 giorni</option><option value={90}>Ultimi 90 giorni</option><option value={365}>Ultimo anno</option></select></div>
<div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={MessageSquare} label="Conversazioni" value={s.conversations}/><Metric icon={TrendingUp} label="Messaggi" value={s.messages}/><Metric icon={CheckCircle2} label="Risoluzione" value={s.conversations?`${Math.round(s.resolved/s.conversations*100)}%`:'—'}/><Metric icon={Star} label="Soddisfazione" value={s.satisfaction===null?'—':`${s.satisfaction}%`}/><Metric icon={UserRoundCheck} label="Handoff" value={s.handoffs}/><Metric icon={Users} label="Contatti identificati" value={s.identifiedContacts}/></div>
<div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="card p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold text-gray-900">Conversazioni nel tempo</h2><p className="mt-1 text-[10px] text-gray-400">Aggregazione giornaliera reale</p></div><span className="text-[10px] font-semibold text-brand-600">MEDIA {s.averageMessages} MSG/CHAT</span></div><DailyChart points={data.daily}/></section><Distribution title="Intenti principali" items={data.intents} total={s.conversations}/></div>
<div className="mt-5 grid gap-5 xl:grid-cols-2"><AgentTable agents={data.byAgent}/><Distribution title="Sentiment rilevato" items={data.sentiments} total={s.conversations}/></div>
<PipelinePanel pipeline={data.pipeline}/>
<div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="card overflow-hidden"><div className="border-b px-5 py-4"><div className="flex items-center gap-2"><UserRoundCheck className="h-4 w-4 text-amber-500"/><h2 className="text-sm font-semibold text-gray-900">Conversazioni da gestire</h2></div><p className="mt-1 text-[10px] text-gray-400">Handoff aperti che richiedono attenzione</p></div><div className="divide-y">{data.attention.map(item=><Link href={`/conversations?conversation=${item.id}`} key={item.id} className="flex items-center gap-3 px-5 py-3 hover:bg-gray-50"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-amber-50 text-amber-600"><Users className="h-3.5 w-3.5"/></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-gray-800">{item.name}</p><p className="truncate text-[10px] text-gray-400">{item.agent} · {item.reason||'Handoff richiesto'}</p></div><span className="text-[9px] text-gray-400">Apri</span></Link>)}{!data.attention.length&&<Empty text="Nessun handoff aperto."/>}</div></section><section className="card overflow-hidden"><div className="border-b px-5 py-4"><div className="flex items-center gap-2"><ThumbsDown className="h-4 w-4 text-red-500"/><h2 className="text-sm font-semibold text-gray-900">Feedback negativi</h2></div><p className="mt-1 text-[10px] text-gray-400">Risposte da usare per migliorare prompt e fonti</p></div><div className="divide-y">{data.negativeFeedback.map(item=><Link href={`/conversations?conversation=${item.conversationId}`} key={item.id} className="block px-5 py-3 hover:bg-gray-50"><p className="line-clamp-2 text-xs text-gray-700">{item.content}</p><p className="mt-1 text-[10px] text-red-500">{item.feedbackComment||'Nessun commento aggiunto'}</p></Link>)}{!data.negativeFeedback.length&&<Empty text="Nessun feedback negativo nel periodo."/>}</div></section></div></div></DashboardLayout>}
function Metric({icon:Icon,label,value}:{icon:typeof BarChart3;label:string;value:string|number}){return <div className="card p-4"><div className="flex items-center justify-between"><Icon className="h-4 w-4 text-brand-500"/><span className="text-[9px] uppercase tracking-wider text-gray-400">{label}</span></div><p className="mt-4 text-2xl font-bold text-gray-950">{value}</p></div>}
function DailyChart({points}:{points:{date:string;value:number}[]}){const max=Math.max(1,...points.map(p=>p.value));return <div className="mt-6 flex h-56 items-end gap-1.5 border-b border-gray-100 px-1">{points.length?points.map(point=><div key={point.date} className="group relative flex flex-1 items-end"><div className="w-full rounded-t bg-brand-500/80 transition hover:bg-brand-600" style={{height:`${Math.max(5,point.value/max*100)}%`}}/><div className="pointer-events-none absolute -top-10 left-1/2 hidden -translate-x-1/2 rounded bg-gray-950 px-2 py-1 text-[9px] text-white group-hover:block">{point.date}: {point.value}</div></div>):<p className="m-auto text-xs text-gray-400">Nessuna conversazione nel periodo.</p>}</div>}
function Distribution({title,items,total}:{title:string;items:{label:string;value:number}[];total:number}){return <section className="card p-5"><h2 className="text-sm font-semibold text-gray-900">{title}</h2><div className="mt-5 space-y-4">{items.slice(0,7).map(item=><div key={item.label}><div className="mb-1.5 flex justify-between text-xs"><span className="capitalize text-gray-600">{item.label}</span><span className="font-semibold">{item.value}</span></div><div className="h-1.5 rounded-full bg-gray-100"><div className="h-full rounded-full bg-brand-500" style={{width:`${Math.max(5,total?item.value/total*100:0)}%`}}/></div></div>)}{!items.length&&<Empty text="Nessun dato disponibile."/>}</div></section>}
function AgentTable({agents}:{agents:Data['byAgent']}){return <section className="card overflow-hidden"><div className="border-b px-5 py-4"><h2 className="text-sm font-semibold text-gray-900">Performance per agente</h2></div><table className="w-full text-left text-[10px]"><thead className="bg-gray-50 uppercase tracking-wider text-gray-400"><tr><th className="px-5 py-3">Agente</th><th>Chat</th><th>Messaggi</th><th>Risolte</th><th>Handoff</th></tr></thead><tbody className="divide-y">{agents.map(item=><tr key={item.id}><td className="px-5 py-3 font-semibold text-gray-700"><span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-lg bg-brand-50 text-brand-600"><Bot className="h-3 w-3"/></span>{item.name}</td><td>{item.conversations}</td><td>{item.messages}</td><td>{item.resolved}</td><td>{item.handoffs}</td></tr>)}</tbody></table>{!agents.length&&<Empty text="Nessun agente nel periodo."/>}</section>}
function PipelinePanel({pipeline}:{pipeline:Data['pipeline']}){const labels:Record<string,string>={crawl:'Crawl',cleaning:'Pulizia',embedding:'Embedding',retrieval:'Retrieval',reranking:'Reranking',generation:'Generazione',web_search:'Ricerca web'};return <section className="card mt-5 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="text-sm font-semibold text-gray-900">Pipeline RAG · latenza e costo</h2><p className="mt-1 text-[10px] text-gray-400">Misure reali per ogni fase, non stime aggregate della richiesta.</p></div><div className="flex gap-2 text-[10px]"><span className="rounded-lg bg-brand-50 px-2.5 py-1.5 font-semibold text-brand-700">${pipeline.aiCostUsd.toFixed(4)}</span><span className="rounded-lg bg-gray-100 px-2.5 py-1.5 text-gray-600">{pipeline.aiTokens.toLocaleString('it-IT')} token</span></div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-gray-50 text-[9px] uppercase tracking-wider text-gray-400"><tr><th className="px-5 py-3">Fase</th><th>Chiamate</th><th>Latenza media</th><th>Successo</th><th>Token</th><th>Costo</th></tr></thead><tbody className="divide-y">{pipeline.stages.map(stage=><tr key={stage.stage}><td className="px-5 py-3 font-semibold text-gray-700">{labels[stage.stage]||stage.stage}</td><td>{stage.calls}</td><td>{stage.averageLatencyMs} ms</td><td>{stage.successRate}%</td><td>{stage.totalTokens.toLocaleString('it-IT')}</td><td>${stage.totalCostUsd.toFixed(5)}</td></tr>)}</tbody></table>{!pipeline.stages.length&&<Empty text="Le metriche appariranno dopo i prossimi crawl e conversazioni."/>}</div></section>}
function Empty({text}:{text:string}){return <p className="px-5 py-10 text-center text-xs text-gray-400">{text}</p>}
