'use client'

import { useCallback, useEffect, useState } from 'react'
import { Calendar, CheckCircle2, Code2, Loader2, Plus, Send, Trash2, UserRoundCheck, Users } from 'lucide-react'
import { DashboardLayout } from '@/components/DashboardLayout'
import { Button } from '@/components/ui/Button'

interface Agent { id: string; companyName: string }
interface Execution { id: string; success: boolean; output?: string; error?: string; durationMs?: number; createdAt: string }
interface Action { id: string; name: string; type: string; description?: string; triggerKeywords: string[]; config: Record<string, string>; enabled: boolean; executions: Execution[] }
const types = [
  { id: 'booking_link', name: 'Prenotazione', text: 'Mostra un pulsante verso Calendly o un calendario.', icon: Calendar },
  { id: 'collect_lead', name: 'Raccogli contatto', text: 'Salva email o telefono trovati nel messaggio.', icon: UserRoundCheck },
  { id: 'handoff', name: 'Passa a operatore', text: 'Segnala la conversazione nella inbox umana.', icon: Users },
  { id: 'webhook', name: 'Webhook', text: 'Invia i dati a un endpoint HTTPS esterno.', icon: Code2 },
]
export default function ActionsPage() {
  const [agents, setAgents] = useState<Agent[]>([]), [botId, setBotId] = useState(''), [actions, setActions] = useState<Action[]>([]), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [form, setForm] = useState({ name: '', type: 'booking_link', keywords: '', url: '', label: '', reason: '' })
  useEffect(() => { fetch('/api/chatbots').then(r => r.json()).then(result => { const list = result.data || []; setAgents(list); if (list[0]) setBotId(list[0].id) }) }, [])
  const load = useCallback(async () => { if (!botId) return; const result = await fetch(`/api/actions?botId=${botId}`).then(r => r.json()); setActions(result.data || []) }, [botId])
  useEffect(() => { load() }, [load])
  const create = async () => { setBusy(true); setError(''); const config = form.type === 'booking_link' ? { url: form.url, label: form.label || 'Prenota appuntamento' } : form.type === 'webhook' ? { url: form.url } : form.type === 'handoff' ? { reason: form.reason || 'Richiesta operatore' } : {}; const response = await fetch('/api/actions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ botId, name: form.name, type: form.type, triggerKeywords: form.keywords.split(',').map(item => item.trim()).filter(Boolean), config }) }); const result = await response.json(); if (!response.ok) setError(result.error); else { setOpen(false); setForm({ name: '', type: 'booking_link', keywords: '', url: '', label: '', reason: '' }); await load() } setBusy(false) }
  const toggle = async (action: Action) => { await fetch(`/api/actions/${action.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled: !action.enabled }) }); load() }
  const remove = async (id: string) => { await fetch(`/api/actions/${id}`, { method: 'DELETE' }); load() }
  return <DashboardLayout><div className="mx-auto max-w-[1500px] p-4 lg:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Agent tools</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Actions</h1><p className="mt-1 text-sm text-gray-500">Permetti agli agenti di raccogliere lead, prenotare, trasferire e chiamare servizi reali.</p></div><Button onClick={() => setOpen(true)} disabled={!botId} icon={<Plus className="h-4 w-4" />}>Nuova azione</Button></div>
    <div className="mt-6 card p-4"><label className="label">Agente</label><select className="input max-w-md" value={botId} onChange={e => setBotId(e.target.value)}>{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.companyName}</option>)}</select></div>
    {!actions.length ? <div className="card mt-5 flex min-h-96 flex-col items-center justify-center text-center"><Send className="h-9 w-9 text-brand-600" /><h2 className="mt-3 text-sm font-semibold">Nessuna azione configurata</h2><p className="mt-1 max-w-sm text-xs leading-5 text-gray-500">Crea operazioni attivate da parole chiave. Ogni esecuzione verrà registrata e verificabile.</p></div> : <div className="mt-5 grid gap-4 lg:grid-cols-2">{actions.map(action => { const definition = types.find(item => item.id === action.type) || types[0], latest = action.executions[0]; return <article key={action.id} className="card p-5"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><definition.icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">{action.name}</h2><button onClick={() => toggle(action)} className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${action.enabled ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-500'}`}>{action.enabled ? 'Attiva' : 'Pausa'}</button></div><p className="mt-1 text-[11px] text-gray-500">{definition.text}</p></div><button onClick={() => remove(action.id)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div><div className="mt-4 flex flex-wrap gap-2">{action.triggerKeywords.map(word => <span key={word} className="rounded-md bg-gray-50 px-2 py-1 text-[9px] text-gray-600">“{word}”</span>)}</div>{latest && <div className={`mt-4 rounded-lg p-3 text-[10px] ${latest.success ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}><div className="flex items-center gap-2">{latest.success && <CheckCircle2 className="h-3.5 w-3.5" />}<span className="font-semibold">{latest.success ? latest.output : latest.error}</span><span className="ml-auto opacity-60">{latest.durationMs || 0} ms · {new Date(latest.createdAt).toLocaleString('it-IT')}</span></div></div>}</article> })}</div>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-hard"><p className="eyebrow">Nuova automazione</p><h2 className="mt-1 text-xl font-bold">Configura un’azione</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{types.map(type => <button key={type.id} onClick={() => setForm({ ...form, type: type.id })} className={`rounded-xl border p-4 text-left ${form.type === type.id ? 'border-brand-400 bg-brand-50' : 'border-gray-200'}`}><type.icon className="h-4 w-4 text-brand-600" /><p className="mt-2 text-xs font-semibold">{type.name}</p><p className="mt-1 text-[10px] leading-4 text-gray-500">{type.text}</p></button>)}</div><div className="mt-5 space-y-3"><label className="block"><span className="label">Nome azione</span><input className="input" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="block"><span className="label">Parole di attivazione, separate da virgola</span><input className="input" value={form.keywords} onChange={e => setForm({ ...form, keywords: e.target.value })} placeholder="prenota, appuntamento, consulenza" /></label>{(form.type === 'booking_link' || form.type === 'webhook') && <label className="block"><span className="label">URL HTTPS</span><input className="input" type="url" value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} placeholder="https://..." /></label>}{form.type === 'booking_link' && <label className="block"><span className="label">Testo pulsante</span><input className="input" value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} placeholder="Prenota ora" /></label>}{form.type === 'handoff' && <label className="block"><span className="label">Motivo handoff</span><input className="input" value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></label>}{error && <p className="rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}</div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setOpen(false)}>Annulla</Button><Button onClick={create} disabled={busy || !form.name.trim() || !form.keywords.trim()} icon={busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}>Crea azione</Button></div></div></div>}
  </div></DashboardLayout>
}
