'use client'

import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AlertTriangle, Check, Database, FlaskConical, Loader2, Plug, Trash2, UserRoundCheck, Zap } from 'lucide-react'
import { DashboardLayout } from '@/components/DashboardLayout'
import { Button } from '@/components/ui/Button'
import type { Notification } from '@/components/NotificationCenter'
const icons: Record<string, typeof AlertTriangle> = { handoff: UserRoundCheck, source: Database, evaluation: FlaskConical, action: Zap, integration: Plug }
export default function NotificationsPage() {
  const router = useRouter()
  const [items, setItems] = useState<Notification[]>([]), [loading, setLoading] = useState(true), [filter, setFilter] = useState('all')
  const load = useCallback(() => fetch('/api/notifications?limit=100').then(r => r.json()).then(result => setItems(result.data || [])).finally(() => setLoading(false)), [])
  useEffect(() => { load() }, [load])
  const action = async (item: Notification, dismissed = false) => { await fetch('/api/notifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: item.key, dismissed }) }); if (dismissed) load(); else { router.push(item.href); load() } }
  const filtered = items.filter(item => filter === 'all' || filter === 'unread' && !item.read || item.type === filter)
  return <DashboardLayout><div className="mx-auto max-w-5xl p-4 lg:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Operations center</p><h1 className="mt-1 text-2xl font-bold">Notifiche</h1><p className="mt-1 text-sm text-gray-500">Handoff, regressioni, fonti e connessioni che richiedono attenzione.</p></div><Button variant="secondary" onClick={async () => { await fetch('/api/notifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ all: true, keys: items.map(item => item.key) }) }); load() }} icon={<Check className="h-4 w-4" />}>Segna tutte come lette</Button></div><div className="mt-6 flex flex-wrap gap-2">{[['all','Tutte'],['unread','Non lette'],['handoff','Handoff'],['evaluation','Valutazioni'],['source','Fonti'],['action','Azioni'],['integration','Integrazioni']].map(([key,label]) => <button key={key} onClick={() => setFilter(key)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold ${filter === key ? 'bg-brand-600 text-white' : 'border bg-white text-gray-500'}`}>{label}</button>)}</div>{loading ? <div className="card mt-5 flex h-80 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-brand-600" /></div> : <div className="mt-5 space-y-3">{filtered.map(item => { const Icon = icons[item.type] || AlertTriangle; return <article key={item.key} className={`card flex items-start gap-4 p-5 ${item.read ? 'opacity-65' : ''}`}><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${item.severity === 'critical' ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600'}`}><Icon className="h-5 w-5" /></div><button onClick={() => action(item)} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">{item.title}</h2>{!item.read && <span className="rounded-full bg-brand-50 px-2 py-0.5 text-[8px] font-semibold text-brand-600">Nuova</span>}</div><p className="mt-1 text-[11px] leading-5 text-gray-500">{item.description}</p><p className="mt-2 text-[9px] text-gray-400">{new Date(item.createdAt).toLocaleString('it-IT')}</p></button><button onClick={() => action(item, true)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600" title="Rimuovi"><Trash2 className="h-4 w-4" /></button></article> })}{!filtered.length && <div className="card flex h-80 flex-col items-center justify-center text-center"><Check className="h-9 w-9 text-emerald-500" /><h2 className="mt-3 text-sm font-semibold">Nessuna notifica</h2><p className="mt-1 text-xs text-gray-400">Non ci sono eventi per questo filtro.</p></div>}</div>}</div></DashboardLayout>
}
