'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Bot, Database, GitBranch, Loader2, MessageSquare, Plug, Search, Settings2, Zap } from 'lucide-react'

interface Result { id: string; type: string; title: string; subtitle: string; href: string }
const icons: Record<string, typeof Bot> = { Agente: Bot, Conversazione: MessageSquare, Fonte: Database, Workflow: GitBranch, Azione: Zap, Integrazione: Plug }
const shortcuts: Result[] = [
  { id: 'new-agent', type: 'Azione rapida', title: 'Crea nuovo agente', subtitle: 'Avvia la configurazione guidata', href: '#create-agent' },
  { id: 'templates', type: 'Navigazione', title: 'Apri Templates Marketplace', subtitle: 'Crea da una configurazione pronta', href: '/templates' },
  { id: 'settings', type: 'Navigazione', title: 'Impostazioni di sistema', subtitle: 'Controlla servizi e sicurezza', href: '/settings' },
]
export function GlobalSearch() {
  const router = useRouter()
  const [open, setOpen] = useState(false), [query, setQuery] = useState(''), [results, setResults] = useState<Result[]>([]), [loading, setLoading] = useState(false), [active, setActive] = useState(0)
  const input = useRef<HTMLInputElement>(null)
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(value => !value) } if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [])
  useEffect(() => { if (open) setTimeout(() => input.current?.focus(), 20); else { setQuery(''); setResults([]) } }, [open])
  useEffect(() => { if (query.trim().length < 2) { setResults([]); setLoading(false); return }; setLoading(true); const controller = new AbortController(), timer = setTimeout(() => fetch(`/api/search?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then(r => r.json()).then(result => { setResults(result.data || []); setActive(0) }).finally(() => setLoading(false)), 220); return () => { clearTimeout(timer); controller.abort() } }, [query])
  const visible = query.trim().length < 2 ? shortcuts : results
  const choose = (item: Result) => { setOpen(false); if (item.href === '#create-agent') window.dispatchEvent(new Event('open-create-modal')); else router.push(item.href) }
  return <><button onClick={() => setOpen(true)} className="flex h-9 w-full max-w-md items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 px-3 text-left text-sm text-gray-400 transition hover:bg-white"><Search className="h-4 w-4" /><span className="flex-1 truncate">Cerca agenti, conversazioni, fonti...</span><kbd className="rounded border bg-white px-1.5 py-0.5 text-[9px] font-semibold text-gray-400">Ctrl K</kbd></button>
    {open && <div className="fixed inset-0 z-[70] flex items-start justify-center bg-gray-950/45 p-4 pt-[12vh] backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && setOpen(false)}><div className="w-full max-w-2xl overflow-hidden rounded-2xl border border-white/10 bg-white shadow-2xl"><div className="flex items-center gap-3 border-b px-5 py-4"><Search className="h-5 w-5 text-brand-600" /><input ref={input} value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'ArrowDown') { e.preventDefault(); setActive(value => Math.min(value + 1, visible.length - 1)) } if (e.key === 'ArrowUp') { e.preventDefault(); setActive(value => Math.max(value - 1, 0)) } if (e.key === 'Enter' && visible[active]) choose(visible[active]) }} className="min-w-0 flex-1 border-0 bg-transparent text-base outline-none" placeholder="Cerca ovunque..." />{loading && <Loader2 className="h-4 w-4 animate-spin text-brand-600" />}<kbd className="rounded bg-gray-100 px-2 py-1 text-[10px] text-gray-500">Esc</kbd></div><div className="max-h-[55vh] overflow-y-auto p-2">{visible.map((item, index) => { const Icon = icons[item.type] || (item.type === 'Azione rapida' ? Zap : Settings2); return <button key={`${item.type}-${item.id}`} onMouseEnter={() => setActive(index)} onClick={() => choose(item)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left ${active === index ? 'bg-brand-50' : 'hover:bg-gray-50'}`}><div className={`flex h-9 w-9 items-center justify-center rounded-lg ${active === index ? 'bg-brand-600 text-white' : 'bg-gray-100 text-gray-500'}`}><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-xs font-semibold text-gray-900">{item.title}</p><span className="rounded bg-gray-100 px-1.5 py-0.5 text-[8px] font-semibold uppercase text-gray-400">{item.type}</span></div><p className="mt-0.5 truncate text-[10px] text-gray-500">{item.subtitle}</p></div></button> })}{!loading && query.length >= 2 && !visible.length && <div className="p-12 text-center"><Search className="mx-auto h-7 w-7 text-gray-300" /><p className="mt-3 text-xs font-semibold text-gray-600">Nessun risultato</p><p className="mt-1 text-[10px] text-gray-400">Prova nome cliente, email, fonte o workflow.</p></div>}</div><div className="flex gap-4 border-t bg-gray-50 px-5 py-2.5 text-[9px] text-gray-400"><span>↑↓ naviga</span><span>Invio apri</span><span>Esc chiudi</span></div></div></div>}
  </>
}
