'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { Bot, Check, ExternalLink, Loader2, Plug, Search, Settings2, Unplug, Wifi } from 'lucide-react'
import { Button } from '@/components/ui/Button'

interface Agent { id: string; companyName: string }
interface Connection { id: string; enabled: boolean; status: string; config: Record<string, string>; lastTestedAt?: string; lastError?: string }
interface Integration { provider: string; name: string; category: string; description: string; color: string; initials: string; mode: 'native' | 'configuration' | 'planned'; fields?: Array<{ key: string; label: string; placeholder: string; type?: string }>; connection: Connection | null }

const categoryNames: Record<string, string> = { all: 'Tutte', channels: 'Canali', crm: 'CRM', calendar: 'Calendario', automation: 'Automazioni', commerce: 'E-commerce', support: 'Supporto', data: 'Dati' }

export function IntegrationMarketplace({ initialCategory = 'all' }: { initialCategory?: string }) {
  const [agents, setAgents] = useState<Agent[]>([]), [botId, setBotId] = useState(''), [items, setItems] = useState<Integration[]>([])
  const [category, setCategory] = useState(initialCategory), [search, setSearch] = useState(''), [editing, setEditing] = useState<Integration | null>(null), [config, setConfig] = useState<Record<string, string>>({}), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  useEffect(() => { fetch('/api/chatbots').then(r => r.json()).then(result => { const list = result.success ? result.data : []; setAgents(list); if (list[0]) setBotId(list[0].id) }) }, [])
  const load = useCallback(async () => { if (!botId) return; const result = await fetch(`/api/integrations?botId=${botId}`).then(r => r.json()); setItems(result.data || []) }, [botId])
  useEffect(() => { load() }, [load])
  const filtered = useMemo(() => items.filter(item => (category === 'all' || item.category === category) && `${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase())), [items, category, search])
  const connected = items.filter(item => item.connection?.enabled).length
  const open = (item: Integration) => { setEditing(item); setConfig(item.connection?.config || {}); setMessage('') }
  const save = async () => { if (!editing || !botId) return; setBusy(true); const response = await fetch('/api/integrations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ botId, provider: editing.provider, config, enabled: true }) }); const result = await response.json(); if (!response.ok) setMessage(result.error || 'Configurazione non riuscita'); else { setEditing(null); await load() } setBusy(false) }
  const remove = async (item: Integration) => { if (!item.connection) return; await fetch(`/api/integrations/${item.connection.id}`, { method: 'DELETE' }); await load() }
  const test = async (item: Integration) => { if (!item.connection) return; setBusy(true); const result = await fetch(`/api/integrations/${item.connection.id}/test`, { method: 'POST' }).then(r => r.json()); setMessage(result.success ? 'Connessione verificata correttamente.' : result.error); await load(); setBusy(false) }

  return <div className="mx-auto max-w-[1500px] p-4 lg:p-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{initialCategory === 'channels' ? 'Pubblicazione omnicanale' : 'Connection center'}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-gray-950">{initialCategory === 'channels' ? 'Canali' : 'Integrazioni'}</h1><p className="mt-1 text-sm text-gray-500">Collega strumenti reali all’agente. Le funzioni non ancora disponibili sono indicate chiaramente.</p></div><div className="card flex items-center gap-3 px-4 py-3"><Plug className="h-4 w-4 text-brand-600" /><div><p className="text-[9px] uppercase tracking-wider text-gray-400">Attive</p><p className="text-sm font-bold">{connected}</p></div></div></div>
    <div className="mt-6 card flex flex-wrap items-center gap-3 p-4"><div className="min-w-[220px] flex-1"><label className="label">Agente</label><select className="input" value={botId} onChange={e => setBotId(e.target.value)}>{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.companyName}</option>)}</select></div><div className="relative min-w-[220px] flex-1"><label className="label">Cerca</label><Search className="absolute bottom-3 left-3 h-4 w-4 text-gray-400" /><input className="input pl-9" value={search} onChange={e => setSearch(e.target.value)} placeholder="WhatsApp, CRM, calendario..." /></div></div>
    <div className="mt-4 flex flex-wrap gap-2">{Object.entries(categoryNames).map(([key, label]) => <button key={key} onClick={() => setCategory(key)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold ${category === key ? 'bg-brand-600 text-white' : 'border bg-white text-gray-500'}`}>{label}</button>)}</div>
    {!agents.length ? <div className="card mt-5 flex min-h-80 flex-col items-center justify-center text-center"><Bot className="h-8 w-8 text-brand-600" /><p className="mt-3 text-sm font-semibold">Crea prima un agente</p></div> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item => <article key={item.provider} className="card p-5"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-xs font-bold text-white" style={{ backgroundColor: item.color }}>{item.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold text-gray-900">{item.name}</h2>{item.connection?.enabled && <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[9px] font-semibold text-emerald-700">Attiva</span>}</div><p className="mt-1 min-h-10 text-[11px] leading-5 text-gray-500">{item.description}</p></div></div><div className="mt-4 flex items-center justify-between border-t pt-4"><span className="text-[9px] font-semibold uppercase tracking-wider text-gray-400">{categoryNames[item.category]}</span>{item.mode === 'planned' ? <span className="rounded-lg bg-gray-100 px-3 py-2 text-[10px] font-semibold text-gray-500">Connettore in sviluppo</span> : item.connection ? <div className="flex gap-1"><button onClick={() => open(item)} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100" aria-label="Configura"><Settings2 className="h-4 w-4" /></button><button onClick={() => remove(item)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600" aria-label="Disconnetti"><Unplug className="h-4 w-4" /></button></div> : <Button size="sm" variant="secondary" onClick={() => open(item)} icon={<Plug className="h-3.5 w-3.5" />}>Collega</Button>}</div>{item.connection?.lastError && <p className="mt-3 rounded-lg bg-red-50 p-2 text-[10px] text-red-700">{item.connection.lastError}</p>}</article>)}</div>}
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-hard"><div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl text-xs font-bold text-white" style={{ backgroundColor: editing.color }}>{editing.initials}</div><div><p className="eyebrow">Configurazione</p><h2 className="text-lg font-bold">{editing.name}</h2></div></div><div className="mt-5 space-y-4">{editing.fields?.map(field => <label key={field.key} className="block"><span className="label">{field.label}</span><input className="input" type={field.type || 'text'} value={config[field.key] || ''} onChange={e => setConfig({ ...config, [field.key]: e.target.value })} placeholder={field.placeholder} /></label>)}{editing.mode === 'native' && <div className="rounded-xl bg-emerald-50 p-4 text-xs leading-5 text-emerald-700"><Check className="mb-2 h-4 w-4" />Questa funzione è già inclusa nella piattaforma. Attivandola apparirà tra i canali collegati.</div>}{message && <p className={`rounded-lg p-3 text-xs ${message.includes('correttamente') ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{message}</p>}</div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={() => setEditing(null)}>Annulla</Button>{editing.connection && editing.mode === 'configuration' && <Button variant="secondary" onClick={() => test(editing)} disabled={busy} icon={<Wifi className="h-4 w-4" />}>Testa</Button>}<Button onClick={save} disabled={busy} icon={busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}>Salva</Button></div>{editing.provider === 'public-page' && botId && <a className="mt-4 flex items-center justify-center gap-1 text-xs font-semibold text-brand-700" href={`/chat/${botId}`} target="_blank">Apri pagina pubblica <ExternalLink className="h-3 w-3" /></a>}</div></div>}
  </div>
}
