'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AlertTriangle, Bell, Check, Database, FlaskConical, Plug, UserRoundCheck, X, Zap } from 'lucide-react'

export interface Notification { key: string; type: string; severity: string; title: string; description: string; href: string; createdAt: string; read: boolean }
const icons: Record<string, typeof Bell> = { handoff: UserRoundCheck, source: Database, evaluation: FlaskConical, action: Zap, integration: Plug }
export function NotificationCenter() {
  const router = useRouter(), root = useRef<HTMLDivElement>(null)
  const [open, setOpen] = useState(false), [items, setItems] = useState<Notification[]>([]), [unread, setUnread] = useState(0)
  const load = useCallback(() => fetch('/api/notifications?limit=12').then(r => r.json()).then(result => { setItems(result.data || []); setUnread(result.unread || 0) }), [])
  useEffect(() => { load(); const timer = setInterval(load, 60000); return () => clearInterval(timer) }, [load])
  useEffect(() => { const close = (event: MouseEvent) => { if (open && !root.current?.contains(event.target as Node)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open])
  const read = async (item: Notification) => { if (!item.read) await fetch('/api/notifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: item.key }) }); setOpen(false); router.push(item.href); load() }
  const dismiss = async (item: Notification) => { await fetch('/api/notifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: item.key, dismissed: true }) }); load() }
  const readAll = async () => { await fetch('/api/notifications', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ all: true, keys: items.map(item => item.key) }) }); load() }
  return <div ref={root} className="relative"><button onClick={() => setOpen(value => !value)} aria-label={`Notifiche${unread ? `, ${unread} non lette` : ''}`} className="relative rounded-lg p-2 text-gray-500 hover:bg-gray-100"><Bell className="h-4 w-4" />{unread > 0 && <span className="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[8px] font-bold text-white">{unread > 9 ? '9+' : unread}</span>}</button>{open && <div className="absolute right-0 top-11 z-50 w-[380px] overflow-hidden rounded-xl border bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-4 py-3"><div><p className="text-xs font-semibold">Notifiche</p><p className="text-[9px] text-gray-400">{unread} da leggere</p></div>{unread > 0 && <button onClick={readAll} className="flex items-center gap-1 text-[9px] font-semibold text-brand-600"><Check className="h-3 w-3" />Segna tutte</button>}</div><div className="max-h-[460px] overflow-y-auto p-2">{items.map(item => { const Icon = icons[item.type] || AlertTriangle; return <div key={item.key} className={`group flex w-full items-start rounded-lg hover:bg-gray-50 ${item.read ? 'opacity-60' : ''}`}><button onClick={() => read(item)} className="flex min-w-0 flex-1 items-start gap-3 p-3 text-left"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${item.severity === 'critical' ? 'bg-red-50 text-red-600' : 'bg-amber-50 text-amber-600'}`}><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-[11px] font-semibold text-gray-800">{item.title}</p>{!item.read && <span className="h-1.5 w-1.5 rounded-full bg-brand-600" />}</div><p className="mt-1 line-clamp-2 text-[9px] leading-4 text-gray-500">{item.description}</p><p className="mt-1 text-[8px] text-gray-400">{new Date(item.createdAt).toLocaleString('it-IT')}</p></div></button><button onClick={() => dismiss(item)} aria-label={`Ignora notifica: ${item.title}`} className="mr-2 mt-3 rounded p-1 text-gray-300 opacity-0 hover:bg-gray-100 hover:text-gray-600 focus:opacity-100 group-hover:opacity-100"><X className="h-3 w-3" /></button></div> })}{!items.length && <div className="p-10 text-center"><Check className="mx-auto h-7 w-7 text-emerald-500" /><p className="mt-2 text-xs font-semibold">Tutto sotto controllo</p><p className="mt-1 text-[9px] text-gray-400">Nessuna notifica operativa.</p></div>}</div><button onClick={() => { setOpen(false); router.push('/notifications') }} className="w-full border-t bg-gray-50 py-3 text-[10px] font-semibold text-brand-600">Apri centro notifiche</button></div>}</div>
}
