"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Copy, KeyRound, Loader2, LockKeyhole, LogOut, ShieldCheck, Smartphone, Trash2 } from "lucide-react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";

type Session = { id: string; deviceLabel: string | null; createdAt: string; lastUsedAt: string; expiresAt: string; current: boolean };
type Account = { mode: "client"; displayName: string; email: string; mfaEnabled: boolean };
type Setup = { secret: string; provisioningUri: string };

export default function AccountSecurityPage() {
  const router = useRouter();
  const [account, setAccount] = useState<Account | null>(null), [sessions, setSessions] = useState<Session[]>([]), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [currentPassword, setCurrentPassword] = useState(""), [newPassword, setNewPassword] = useState(""), [confirmPassword, setConfirmPassword] = useState("");
  const [setupPassword, setSetupPassword] = useState(""), [setup, setSetup] = useState<Setup | null>(null), [mfaCode, setMfaCode] = useState(""), [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [disablePassword, setDisablePassword] = useState(""), [disableCode, setDisableCode] = useState("");

  const load = useCallback(async () => {
    const [meResponse, sessionsResponse] = await Promise.all([fetch("/api/auth/me", { cache: "no-store" }), fetch("/api/auth/sessions", { cache: "no-store" })]);
    const [me, sessionResult] = await Promise.all([meResponse.json(), sessionsResponse.json()]);
    if (!meResponse.ok || me.data?.mode !== "client" || !sessionsResponse.ok) throw new Error(me.error || sessionResult.error || "Sicurezza account non disponibile");
    setAccount(me.data); setSessions(sessionResult.data || []);
  }, []);

  useEffect(() => { load().catch(reason => setError(reason instanceof Error ? reason.message : "Sicurezza account non disponibile")); }, [load]);
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(""); setMessage(""); try { await action(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Operazione non riuscita"); } finally { setBusy(false); } };
  const request = async (url: string, body?: unknown, method = "POST") => { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Operazione non riuscita"); return result; };

  const changePassword = (event: FormEvent) => { event.preventDefault(); void run(async () => { if (newPassword !== confirmPassword) throw new Error("Le nuove password non coincidono"); const result = await request("/api/auth/password", { currentPassword, newPassword }); setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); setMessage(result.message); await load(); }); };
  const beginMfa = (event: FormEvent) => { event.preventDefault(); void run(async () => { const result = await request("/api/auth/mfa/setup", { password: setupPassword }); setSetup(result.data); setSetupPassword(""); setMessage("Aggiungi la chiave nell’app Authenticator, poi inserisci il codice generato."); }); };
  const enableMfa = (event: FormEvent) => { event.preventDefault(); void run(async () => { const result = await request("/api/auth/mfa/enable", { code: mfaCode }); setRecoveryCodes(result.data.recoveryCodes); setSetup(null); setMfaCode(""); setMessage("Verifica in due passaggi attivata. Salva ora i codici di recupero."); await load(); }); };
  const disableMfa = (event: FormEvent) => { event.preventDefault(); void run(async () => { await request("/api/auth/mfa/disable", { password: disablePassword, code: disableCode }); setDisablePassword(""); setDisableCode(""); setRecoveryCodes([]); setMessage("Verifica in due passaggi disattivata e altre sessioni revocate."); await load(); }); };
  const revokeSession = (session: Session) => void run(async () => { const result = await request(`/api/auth/sessions/${session.id}`, undefined, "DELETE"); if (result.current) { router.replace("/login"); router.refresh(); return; } setMessage("Sessione revocata."); await load(); });
  const revokeOthers = () => void run(async () => { await request("/api/auth/sessions", undefined, "DELETE"); setMessage("Tutte le altre sessioni sono state revocate."); await load(); });

  return <DashboardLayout><div className="mx-auto max-w-5xl p-5 lg:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-brand-600">Account personale</p><h1 className="mt-1 text-2xl font-bold text-gray-950">Sicurezza e dispositivi</h1><p className="mt-2 text-sm text-gray-500">Password, autenticazione a due fattori e sessioni attive del tuo account LitX.</p></div>{account?.mfaEnabled ? <span className="inline-flex items-center gap-2 self-start rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><ShieldCheck className="h-4 w-4"/>MFA attiva</span> : <span className="inline-flex items-center gap-2 self-start rounded-full bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><ShieldCheck className="h-4 w-4"/>MFA consigliata</span>}</div>
    {message&&<p className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{message}</p>}{error&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><LockKeyhole className="h-5 w-5 text-brand-600"/><h2 className="font-bold text-gray-950">Cambia password</h2></div><p className="mt-1 text-xs leading-5 text-gray-500">La modifica mantiene questo dispositivo e scollega automaticamente tutti gli altri.</p><form onSubmit={changePassword} className="mt-5 space-y-3"><Input type="password" label="Password attuale" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} autoComplete="current-password" required/><Input type="password" label="Nuova password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} autoComplete="new-password" minLength={12} required/><Input type="password" label="Conferma nuova password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} autoComplete="new-password" minLength={12} required/><Button type="submit" loading={busy} disabled={newPassword.length<12||confirmPassword.length<12}>Aggiorna password</Button></form></section>
      <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-brand-600"/><h2 className="font-bold text-gray-950">Verifica in due passaggi</h2></div>{!account?<div className="mt-8 flex justify-center"><Loader2 className="h-5 w-5 animate-spin text-brand-600"/></div>:account.mfaEnabled?<form onSubmit={disableMfa} className="mt-4 space-y-3"><p className="rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-800">Attiva dal tuo Authenticator. Per disattivarla servono password e codice corrente o codice di recupero.</p><Input type="password" label="Password attuale" value={disablePassword} onChange={event=>setDisablePassword(event.target.value)} autoComplete="current-password" required/><Input label="Codice Authenticator o recupero" value={disableCode} onChange={event=>setDisableCode(event.target.value)} autoComplete="one-time-code" required/><Button type="submit" variant="secondary" loading={busy}>Disattiva MFA</Button></form>:setup?<form onSubmit={enableMfa} className="mt-4 space-y-3"><a href={setup.provisioningUri} className="block rounded-xl border border-brand-200 bg-brand-50 p-3 text-xs font-semibold text-brand-700">Apri nell’app Authenticator</a><div className="rounded-xl bg-gray-50 p-3"><p className="text-[10px] uppercase tracking-wide text-gray-400">Chiave manuale</p><div className="mt-1 flex items-center gap-2"><code className="min-w-0 flex-1 break-all text-xs font-bold text-gray-800">{setup.secret}</code><button type="button" onClick={()=>void navigator.clipboard.writeText(setup.secret)} aria-label="Copia chiave"><Copy className="h-4 w-4 text-gray-500"/></button></div></div><Input label="Codice a 6 cifre" value={mfaCode} onChange={event=>setMfaCode(event.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code" required/><Button type="submit" loading={busy} disabled={mfaCode.length!==6}>Verifica e attiva</Button></form>:<form onSubmit={beginMfa} className="mt-4 space-y-3"><p className="text-xs leading-5 text-gray-500">Funziona con Google Authenticator, Microsoft Authenticator, 1Password e app TOTP compatibili.</p><Input type="password" label="Conferma la password" value={setupPassword} onChange={event=>setSetupPassword(event.target.value)} autoComplete="current-password" required/><Button type="submit" loading={busy} icon={<ShieldCheck className="h-4 w-4"/>}>Configura MFA</Button></form>}
      {recoveryCodes.length>0&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-bold text-amber-950">Salva questi codici adesso</p><p className="mt-1 text-[11px] leading-5 text-amber-800">Ogni codice funziona una sola volta e non sarà più mostrato.</p><div className="mt-3 grid grid-cols-2 gap-2">{recoveryCodes.map(code=><code key={code} className="rounded bg-white px-2 py-1.5 text-center text-[11px] font-bold">{code}</code>)}</div><button type="button" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-amber-900" onClick={()=>void navigator.clipboard.writeText(recoveryCodes.join("\n"))}><Copy className="h-3.5 w-3.5"/>Copia tutti</button></div>}</section></div>
    <section className="mt-5 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><Smartphone className="h-5 w-5 text-brand-600"/><h2 className="font-bold text-gray-950">Dispositivi collegati</h2></div><p className="mt-1 text-xs text-gray-500">Le sessioni scadono automaticamente dopo 14 giorni.</p></div><Button size="sm" variant="secondary" onClick={revokeOthers} disabled={sessions.filter(session=>!session.current).length===0||busy} icon={<LogOut className="h-4 w-4"/>}>Scollega gli altri</Button></div><div className="mt-4 divide-y divide-gray-100 rounded-xl border border-gray-100">{sessions.map(session=><div key={session.id} className="flex items-center gap-3 p-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gray-50 text-gray-500"><Smartphone className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold text-gray-900">{session.deviceLabel||"Dispositivo"}</p>{session.current&&<span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[9px] font-bold text-emerald-700">Questo dispositivo</span>}</div><p className="mt-0.5 text-[10px] text-gray-400">Ultimo utilizzo {new Date(session.lastUsedAt).toLocaleString("it-IT")} · creata {new Date(session.createdAt).toLocaleDateString("it-IT")}</p></div><button type="button" disabled={busy} onClick={()=>revokeSession(session)} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-600" aria-label={session.current?"Esci da questo dispositivo":"Revoca sessione"}><Trash2 className="h-4 w-4"/></button></div>)}{!sessions.length&&<p className="p-5 text-center text-xs text-gray-500">Nessuna sessione attiva.</p>}</div></section>
  </div></DashboardLayout>;
}
