'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, FileSpreadsheet, FileText, FileType2, Loader2, Upload, X } from 'lucide-react'
import { DashboardLayout } from '@/components/DashboardLayout'
import { Button } from '@/components/ui/Button'

interface Agent { id: string; companyName: string }
interface Preview { filename?: string; title?: string; type: string; characters: number; words: number; preview: string; truncated: boolean; warnings: string[] }
export default function ImportKnowledgePage() {
  const [agents, setAgents] = useState<Agent[]>([]), [botId, setBotId] = useState(''), [mode, setMode] = useState<'file' | 'manual'>('file'), [file, setFile] = useState<File | null>(null), [title, setTitle] = useState(''), [content, setContent] = useState(''), [preview, setPreview] = useState<Preview | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [completed, setCompleted] = useState<{ chunks: number; sourceId: string } | null>(null)
  useEffect(() => { fetch('/api/chatbots').then(r => r.json()).then(result => { const list = result.data || []; setAgents(list); if (list[0]) setBotId(list[0].id) }) }, [])
  const reset = () => { setPreview(null); setCompleted(null); setError('') }
  const request = async (previewOnly: boolean) => {
    if (!botId) return
    setBusy(true); setError('')
    try {
      let response: Response
      if (mode === 'file') {
        if (!file) throw new Error('Seleziona un documento')
        const form = new FormData(); form.set('botId', botId); form.set('file', file); form.set('previewOnly', String(previewOnly))
        response = await fetch('/api/knowledge-sources/upload-document', { method: 'POST', body: form })
      } else {
        response = await fetch('/api/knowledge-sources/manual', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ botId, title, content, previewOnly }) })
      }
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || 'Importazione non riuscita')
      if (previewOnly) setPreview(result.data)
      else { setCompleted({ chunks: result.data.chunks, sourceId: result.data.sourceId }); setPreview(result.data) }
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Operazione non riuscita') }
    finally { setBusy(false) }
  }
  return <DashboardLayout><div className="mx-auto max-w-6xl p-4 lg:p-7"><div className="flex items-center gap-3"><Link href="/knowledge" className="rounded-lg border bg-white p-2 text-gray-500"><ArrowLeft className="h-4 w-4" /></Link><div><p className="eyebrow">Knowledge ingestion</p><h1 className="mt-1 text-2xl font-bold">Importa contenuti</h1><p className="mt-1 text-sm text-gray-500">Controlla il testo estratto prima di indicizzarlo nell’agente.</p></div></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[380px_minmax(0,1fr)]"><aside className="space-y-5"><div className="card p-5"><label className="label">Agente destinatario</label><select className="input" value={botId} onChange={event => { setBotId(event.target.value); reset() }}>{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.companyName}</option>)}</select><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={() => { setMode('file'); reset() }} className={`rounded-xl border p-4 text-left ${mode === 'file' ? 'border-brand-400 bg-brand-50' : ''}`}><Upload className="h-4 w-4 text-brand-600" /><p className="mt-2 text-xs font-semibold">Documento</p><p className="mt-1 text-[9px] text-gray-500">PDF, DOCX, TXT, CSV</p></button><button onClick={() => { setMode('manual'); reset() }} className={`rounded-xl border p-4 text-left ${mode === 'manual' ? 'border-brand-400 bg-brand-50' : ''}`}><FileText className="h-4 w-4 text-brand-600" /><p className="mt-2 text-xs font-semibold">Testo manuale</p><p className="mt-1 text-[9px] text-gray-500">FAQ, listini, procedure</p></button></div></div>
      <div className="card p-5">{mode === 'file' ? <><label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-gray-200 bg-gray-50 p-5 text-center hover:border-brand-300"><Upload className="h-7 w-7 text-brand-500" /><p className="mt-3 text-xs font-semibold">{file ? file.name : 'Seleziona o trascina un file'}</p><p className="mt-1 text-[9px] text-gray-400">Massimo 15 MB · PDF, DOCX, TXT, CSV</p><input type="file" accept=".pdf,.docx,.txt,.csv" className="hidden" onChange={event => { setFile(event.target.files?.[0] || null); reset() }} /></label>{file && <div className="mt-3 flex items-center justify-between rounded-lg bg-gray-50 p-3"><span className="text-[10px] text-gray-600">{(file.size / 1024).toFixed(1)} KB</span><button onClick={() => { setFile(null); reset() }} className="text-gray-400"><X className="h-4 w-4" /></button></div>}</> : <div className="space-y-3"><label className="block"><span className="label">Titolo fonte</span><input className="input" value={title} onChange={event => { setTitle(event.target.value); reset() }} placeholder="FAQ servizi e prezzi" /></label><label className="block"><span className="label">Contenuto verificato</span><textarea className="textarea min-h-72 text-xs leading-5" value={content} onChange={event => { setContent(event.target.value); reset() }} placeholder={'Domanda: Quali servizi offrite?\\nRisposta: ...'} /></label></div>}<Button fullWidth className="mt-4" variant="secondary" onClick={() => request(true)} disabled={busy || (mode === 'file' ? !file : title.length < 2 || content.length < 50)} icon={busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <FileText className="h-4 w-4" />}>Genera anteprima</Button>{error && <p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}</div></aside>
      <section className="card min-h-[650px] overflow-hidden">{completed ? <div className="flex h-full min-h-[650px] flex-col items-center justify-center p-8 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><Check className="h-7 w-7" /></div><h2 className="mt-4 text-lg font-bold">Fonte indicizzata</h2><p className="mt-2 text-xs text-gray-500">Sono stati creati {completed.chunks} blocchi semantici pronti per il chatbot.</p><div className="mt-5 flex gap-2"><Button variant="secondary" onClick={() => { setFile(null); setTitle(''); setContent(''); reset() }}>Importa un’altra fonte</Button><Link href="/knowledge" className="btn btn-primary">Torna alle fonti</Link></div></div> : preview ? <div className="flex h-full flex-col"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-brand-50 text-brand-600">{preview.type === 'csv' ? <FileSpreadsheet className="h-5 w-5" /> : preview.type === 'docx' ? <FileType2 className="h-5 w-5" /> : <FileText className="h-5 w-5" />}</div><div><h2 className="text-sm font-semibold">{preview.filename || preview.title}</h2><p className="text-[9px] uppercase tracking-wider text-gray-400">{preview.type} · {preview.words.toLocaleString('it-IT')} parole · {preview.characters.toLocaleString('it-IT')} caratteri</p></div></div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[9px] font-semibold text-amber-700">Non ancora indicizzato</span></div>{preview.warnings.length > 0 && <div className="border-b bg-amber-50 px-5 py-3 text-[10px] text-amber-700">{preview.warnings.join(' · ')}</div>}<div className="flex-1 overflow-y-auto bg-gray-50 p-5"><pre className="whitespace-pre-wrap rounded-xl border bg-white p-5 text-[11px] leading-6 text-gray-700 shadow-sm">{preview.preview}</pre>{preview.truncated && <p className="mt-3 text-center text-[9px] text-gray-400">Anteprima limitata ai primi 8.000 caratteri.</p>}</div><div className="flex items-center justify-between border-t p-4"><p className="max-w-md text-[9px] leading-4 text-gray-400">Confermando, il contenuto verrà suddiviso, trasformato in embeddings e reso disponibile all’agente.</p><Button onClick={() => request(false)} disabled={busy} icon={busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}>{busy ? 'Indicizzazione...' : 'Conferma e indicizza'}</Button></div></div> : <div className="flex h-full min-h-[650px] flex-col items-center justify-center p-8 text-center"><FileText className="h-10 w-10 text-gray-300" /><h2 className="mt-4 text-sm font-semibold">Anteprima del contenuto</h2><p className="mt-2 max-w-sm text-xs leading-5 text-gray-400">Seleziona un documento o inserisci testo manuale. Potrai verificare cosa verrà appreso prima dell’indicizzazione.</p></div>}</section></div>
  </div></DashboardLayout>
}
