"use client";

import { FormEvent, Suspense, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Bot, CheckCircle2, Loader2, LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/Button";

export default function ResetPasswordPage(){return <Suspense fallback={<main className="min-h-screen bg-gray-950"/>}><ResetPasswordForm/></Suspense>}
function ResetPasswordForm(){
  const token=useSearchParams().get("token")||""; const [password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[done,setDone]=useState(false),[loading,setLoading]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(password!==confirm)return setError("Le password non coincidono");setLoading(true);setError("");const response=await fetch("/api/auth/password-reset/confirm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password})});const result=await response.json();setLoading(false);if(!response.ok)return setError(result.error||"Reimpostazione non riuscita");setDone(true)};
  return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-gray-950 p-5"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(99,60,255,0.3),_transparent_42%)]"/><section className="relative w-full max-w-md rounded-3xl border border-white/10 bg-white p-7 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-600 text-white"><Bot className="h-5 w-5"/></div><div><p className="text-lg font-bold text-gray-950">LitX AI</p><p className="text-[10px] uppercase tracking-widest text-gray-400">Nuova password</p></div></div>{done?<div className="mt-7 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="mt-4 text-xl font-bold">Password aggiornata</h1><p className="mt-2 text-sm text-gray-500">Tutte le sessioni precedenti sono state revocate.</p><Link href="/login" className="btn btn-primary mt-5 inline-flex">Vai al login</Link></div>:<form onSubmit={submit}><h1 className="mt-7 text-xl font-bold text-gray-950">Scegli una password nuova</h1><p className="mt-2 text-xs leading-5 text-gray-500">Usa almeno 12 caratteri e una password diversa da quelle impiegate altrove.</p><label className="mt-5 block"><span className="label">Nuova password</span><div className="relative"><LockKeyhole className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400"/><input autoFocus type="password" value={password} onChange={event=>setPassword(event.target.value)} className="input pl-9" autoComplete="new-password" minLength={12} required/></div></label><label className="mt-4 block"><span className="label">Conferma password</span><input type="password" value={confirm} onChange={event=>setConfirm(event.target.value)} className="input" autoComplete="new-password" minLength={12} required/></label>{!token&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-700">Link di recupero non valido.</p>}{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<Button type="submit" fullWidth className="mt-5" disabled={!token||password.length<12||confirm.length<12||loading} icon={loading?<Loader2 className="h-4 w-4 animate-spin"/>:<LockKeyhole className="h-4 w-4"/>}>Aggiorna password</Button></form>}</section></main>;
}
