'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Bookmark, Bot, BrainCircuit, Check, ChevronRight, Database, FlaskConical, GitBranch, Lightbulb, Loader2, MessageSquareWarning, Plug, Sparkles, X } from 'lucide-react'
import { DashboardLayout } from '@/components/DashboardLayout'
import { Button } from '@/components/ui/Button'

interface Agent { id: string; companyName: string }
interface Suggestion { id: string; botId: string; category: string; title: string; description: string; impact: 'high' | 'medium' | 'low'; status: string; actionType: string; evidence: Record<string, unknown>; chatbot?: { companyName: string } }
const categoryIcons: Record<string, typeof Bot> = { knowledge: Database, prompt: BrainCircuit, testing: FlaskConical, conversations: MessageSquareWarning, workflow: GitBranch, automation: Sparkles, channels: Plug, commerce: Sparkles }
const destinations: Record<string, string> = { open_knowledge: '/knowledge', open_evaluations: '/evaluations', open_negative_feedback: '/analytics', open_actions: '/actions', open_channels: '/channels', open_integrations: '/integrations', open_commerce: '/commerce' }
export default function SuggestionsPage() {
  const router = useRouter()
  const [agents, setAgents] = useState<Agent[]>([]), [botId, setBotId] = useState('all'), [status, setStatus] = useState('pending'), [items, setItems] = useState<Suggestion[]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState('')
  useEffect(() => { fetch('/api/chatbots').then(r => r.json()).then(result => setAgents(result.data || [])) }, [])
  const load = useCallback(async () => { setLoading(true); const query = new URLSearchParams({ status }); if (botId !== 'all') query.set('botId', botId); const result = await fetch(`/api/suggestions?${query}`).then(r => r.json()); setItems(result.data || []); setLoading(false) }, [botId, status])
  useEffect(() => { load() }, [load])
  const counts = useMemo(() => ({ high: items.filter(item => item.impact === 'high').length, medium: items.filter(item => item.impact === 'medium').length }), [items])
  const setSuggestionStatus = async (item: Suggestion, next: string) => { setBusy(item.id); await fetch(`/api/suggestions/${item.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: next }) }); await load(); setBusy('') }
  const apply = async (item: Suggestion) => { setBusy(item.id); const response = await fetch(`/api/suggestions/${item.id}/apply`, { method: 'POST' }); if (response.ok) { const destination = destinations[item.actionType]; if (destination) router.push(destination); else await load() } setBusy('') }
  return <DashboardLayout><div className="mx-auto max-w-[1400px] p-4 lg:p-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Continuous improvement</p><h1 className="mt-1 text-2xl font-bold tracking-tight">AI Suggestions</h1><p className="mt-1 text-sm text-gray-500">Priorità generate da fonti, conversazioni, feedback e test reali della piattaforma.</p></div><div className="flex gap-3"><Metric label="Priorità alta" value={counts.high} tone="red" /><Metric label="Da migliorare" value={counts.medium} tone="amber" /></div></div>
    <div className="mt-6 card flex flex-wrap items-end gap-3 p-4"><label className="min-w-[220px] flex-1"><span className="label">Agente</span><select className="input" value={botId} onChange={e => setBotId(e.target.value)}><option value="all">Tutti gli agenti</option>{agents.map(agent => <option key={agent.id} value={agent.id}>{agent.companyName}</option>)}</select></label><div className="flex gap-2">{[['pending','Da valutare'],['saved','Salvati'],['dismissed','Ignorati']].map(([key,label]) => <button key={key} onClick={() => setStatus(key)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold ${status === key ? 'bg-brand-600 text-white' : 'border bg-white text-gray-500'}`}>{label}</button>)}</div></div>
    {loading ? <div className="card mt-5 flex min-h-96 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-brand-600" /></div> : !items.length ? <div className="card mt-5 flex min-h-96 flex-col items-center justify-center text-center"><Check className="h-9 w-9 text-emerald-500" /><h2 className="mt-3 text-sm font-semibold">{status === 'pending' ? 'Nessuna priorità aperta' : 'Nessun suggerimento in questa sezione'}</h2><p className="mt-1 max-w-sm text-xs leading-5 text-gray-500">Il sistema aggiorna automaticamente i suggerimenti usando lo stato corrente degli agenti.</p></div> : <div className="mt-5 grid gap-4 xl:grid-cols-2">{items.map(item => { const Icon = categoryIcons[item.category] || Lightbulb; return <article key={item.id} className="card p-5"><div className="flex items-start gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.impact === 'high' ? 'bg-red-50 text-red-600' : item.impact === 'medium' ? 'bg-amber-50 text-amber-600' : 'bg-brand-50 text-brand-600'}`}><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${item.impact === 'high' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}>{item.impact === 'high' ? 'Priorità alta' : 'Impatto medio'}</span><span className="text-[9px] font-semibold uppercase tracking-wider text-gray-400">{item.chatbot?.companyName}</span></div><h2 className="mt-2 text-sm font-semibold text-gray-900">{item.title}</h2><p className="mt-1 text-[11px] leading-5 text-gray-500">{item.description}</p></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><span className="text-[9px] uppercase tracking-wider text-gray-400">Evidenza: {Object.values(item.evidence).filter(value => typeof value !== 'object').join(' · ') || 'analisi configurazione'}</span>{status === 'pending' && <div className="flex gap-1"><button onClick={() => setSuggestionStatus(item, 'dismissed')} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100" title="Ignora"><X className="h-4 w-4" /></button><button onClick={() => setSuggestionStatus(item, 'saved')} className="rounded-lg p-2 text-gray-400 hover:bg-brand-50 hover:text-brand-600" title="Salva"><Bookmark className="h-4 w-4" /></button><Button size="sm" onClick={() => apply(item)} disabled={busy === item.id} icon={busy === item.id ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <ChevronRight className="h-3.5 w-3.5" />}>{item.actionType.startsWith('create_') ? 'Applica' : 'Apri e correggi'}</Button></div>}{status !== 'pending' && <Button size="sm" variant="secondary" onClick={() => setSuggestionStatus(item, 'pending')}>Ripristina</Button>}</div></article> })}</div>}
  </div></DashboardLayout>
}
function Metric({ label, value, tone }: { label: string; value: number; tone: 'red' | 'amber' }) { return <div className={`rounded-xl border px-4 py-3 ${tone === 'red' ? 'border-red-100 bg-red-50' : 'border-amber-100 bg-amber-50'}`}><p className={`text-[9px] font-semibold uppercase tracking-wider ${tone === 'red' ? 'text-red-500' : 'text-amber-500'}`}>{label}</p><p className={`mt-1 text-lg font-bold ${tone === 'red' ? 'text-red-700' : 'text-amber-700'}`}>{value}</p></div> }
